#
# Workflow for all checks on the decode_raw binary (see main.rs)
#
name: binary

# Pushes to long living branches and all PRs
on:
  push:
    branches:
      - main
      - 0.[0-9]+
  pull_request:

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.56.1
          target: ${{ matrix.target }}
          override: true

      - uses: actions-rs/cargo@v1
        with:
          command: install
          args: --path .

      - name: Execute binary
        run: decode_raw --version
